name: work-tracker

services:
  frontend:
    build:
      context: ./timely-frontend
    ports:
      - "127.0.0.1:3000:80"
    restart: unless-stopped
  backend:
    ports:
      - "127.0.0.1:8080:8080"
    build:
      context: ./timely-backend
    env_file:
      - ./timely-backend/.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped

  telegram-bot:
    build:
      context: ./timely-telegram-bot
    env_file:
      - ./timely-telegram-bot/.env
    environment:
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend
    restart: unless-stopped
