CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    role VARCHAR(255) NOT NULL DEFAULT 'USER',
    token_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_token_version CHECK (token_version >= 0)
);

CREATE TABLE public.shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    shift_start TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    shift_end TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    shift_duration_minutes BIGINT NOT NULL,

    CONSTRAINT pk_shifts PRIMARY KEY (id),
    CONSTRAINT fk_shifts_user
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE,
    CONSTRAINT ck_shifts_chronological
        CHECK (shift_end >= shift_start),
    CONSTRAINT ck_shifts_duration_non_negative
        CHECK (shift_duration_minutes >= 0)
);

CREATE INDEX idx_shifts_user_id_shift_start
    ON public.shifts (user_id, shift_start);
