CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    full_name VARCHAR(255),
    role VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    shift_start TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    shift_end TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    shift_duration_minutes BIGINT NOT NULL,
    CONSTRAINT fk_shifts_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);
